export const AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_REDIRECT = "LOGIN_REDIRECT";
