export const AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_REDIRECT = "LOGIN_REDIRECT";
export const GET_DRIVERS_SUCCESS = "GET_DRIVERS_SUCCESS";
export const UPDATE_DRIVERS_SUCCESS = "UPDATE_DRIVERS_SUCCESS";
export const SELECT_DRIVER = "SELECT_DRIVER";
